### PR TITLE
Update tokenizer

### PR DESCRIPTION
**Pull request by gustingonzalez**
Changes proposed in this pull request:
- Include tokens of len 1 on tokenization
- Refactor tokenizer.hpp

### CODE REVIEW

**Review by elshize — APPROVED** [review]
Looks good. Is this all you wanted to do in this PR?

**Comment by gustingonzalez** [comment]
> Looks good. Is this all you wanted to do in this PR?
Yes @elshize. I will open other PR for the "tokenization avoidance when using term ids".

**Comment by gustingonzalez** [comment]
> Looks good. Is this all you wanted to do in this PR?

Yes @elshize. I will open other PR for the "tokenization avoidance when using term ids".

**Comment by elshize** [comment]
Alright then, I'm merging and closing.

**Pull request merged**
