### PR TITLE
Fix building with libstdc++10 and up

### PR DESCRIPTION
**Pull request by elshize**

### CODE REVIEW

**Comment by elshize** [comment]
@JMMackenzie would you mind running the header compilation locally and check for errors? I don't get any errors, and I can't access any logs from CI. I'd rather avoid installing another gcc version for this if it can be helped.

**Comment by JMMackenzie** [comment]
> @JMMackenzie would you mind running the header compilation locally and check for errors? I don't get any errors, and I can't access any logs from CI. I'd rather avoid installing another gcc version for this if it can be helped.

`make headers` works fine locally for me as well!

**Comment by JMMackenzie** [comment]
Isn't the header build blowing up with the cmake command?

```
 -- Performing Test IsSelfContained_home_runner_work_pisa_pisa_include_pisa_forward_index_builder_hpp - Failed
 ```
 
 My local version doesn't seem to run those tests?

**Comment by elshize** [comment]
Yep, that's what I meant: `cmake -DCMAKE_BUILD_TYPE=Debug -DPISA_COMPILE_HEADERS=On -DPISA_CI_BUILD=ON ..`

Can you check at the bottom of `build/CMakeFiles/CMakeError.log` what the error was?

**Comment by elshize** [comment]
You can also fix the errors and push changes if you like.

**Comment by JMMackenzie** [comment]
I can only assume this is the issue, a bit going on there.

```
In file included from /home/jmmacke/pisa-dev/build/CMakeFiles/CMakeTmp/src.cxx:1:0:
/home/jmmacke/pisa-dev/include/pisa/forward_index_builder.hpp: In lambda function:
/home/jmmacke/pisa-dev/include/pisa/forward_index_builder.hpp:147:69: error: no matching function for call to ‘inplace_merge(const pstl::execution::v1::parallel_policy&, __gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > >&, __gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > >&, __gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > >&)’
             std::inplace_merge(std::execution::par, first, mid, last);
                                                                     ^
In file included from /usr/include/c++/7/algorithm:62:0,
                 from /home/jmmacke/pisa-dev/include/pisa/forward_index_builder.hpp:3,
                 from /home/jmmacke/pisa-dev/build/CMakeFiles/CMakeTmp/src.cxx:1:
/usr/include/c++/7/bits/stl_algo.h:2574:5: note: candidate: template<class _BIter> void std::inplace_merge(_BIter, _BIter, _BIter)
     inplace_merge(_BidirectionalIterator __first,
     ^~~~~~~~~~~~~
/usr/include/c++/7/bits/stl_algo.h:2574:5: note:   template argument deduction/substitution failed:
In file included from /home/jmmacke/pisa-dev/build/CMakeFiles/CMakeTmp/src.cxx:1:0:
/home/jmmacke/pisa-dev/include/pisa/forward_index_builder.hpp:147:69: note:   deduced conflicting types for parameter ‘_BIter’ (‘pstl::execution::v1::parallel_policy’ and ‘__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > >’)
             std::inplace_merge(std::execution::par, first, mid, last);
                                                                     ^
In file included from /usr/include/c++/7/algorithm:62:0,
                 from /home/jmmacke/pisa-dev/include/pisa/forward_index_builder.hpp:3,
                 from /home/jmmacke/pisa-dev/build/CMakeFiles/CMakeTmp/src.cxx:1:
/usr/include/c++/7/bits/stl_algo.h:2615:5: note: candidate: template<class _BIter, class _Compare> void std::inplace_merge(_BIter, _BIter, _BIter, _Compare)
     inplace_merge(_BidirectionalIterator __first,
     ^~~~~~~~~~~~~
/usr/include/c++/7/bits/stl_algo.h:2615:5: note:   template argument deduction/substitution failed:
In file included from /home/jmmacke/pisa-dev/build/CMakeFiles/CMakeTmp/src.cxx:1:0:
/home/jmmacke/pisa-dev/include/pisa/forward_index_builder.hpp:147:69: note:   deduced conflicting types for parameter ‘_BIter’ (‘pstl::execution::v1::parallel_policy’ and ‘__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > >’)
             std::inplace_merge(std::execution::par, first, mid, last);
                                                                     ^
/home/jmmacke/pisa-dev/include/pisa/forward_index_builder.hpp:148:69: error: no matching function for call to ‘unique(const pstl::execution::v1::parallel_policy&, __gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > >&, __gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > >&)’
             terms.erase(std::unique(std::execution::par, first, last), last);
                                                                     ^
In file included from /usr/include/c++/7/algorithm:62:0,
                 from /home/jmmacke/pisa-dev/include/pisa/forward_index_builder.hpp:3,
                 from /home/jmmacke/pisa-dev/build/CMakeFiles/CMakeTmp/src.cxx:1:
/usr/include/c++/7/bits/stl_algo.h:995:5: note: candidate: template<class _FIter> _FIter std::unique(_FIter, _FIter)
     unique(_ForwardIterator __first, _ForwardIterator __last)
     ^~~~~~
/usr/include/c++/7/bits/stl_algo.h:995:5: note:   template argument deduction/substitution failed:
In file included from /home/jmmacke/pisa-dev/build/CMakeFiles/CMakeTmp/src.cxx:1:0:
/home/jmmacke/pisa-dev/include/pisa/forward_index_builder.hpp:148:69: note:   deduced conflicting types for parameter ‘_FIter’ (‘pstl::execution::v1::parallel_policy’ and ‘__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > >’)
             terms.erase(std::unique(std::execution::par, first, last), last);
                                                                     ^
In file included from /usr/include/c++/7/algorithm:62:0,
                 from /home/jmmacke/pisa-dev/include/pisa/forward_index_builder.hpp:3,
                 from /home/jmmacke/pisa-dev/build/CMakeFiles/CMakeTmp/src.cxx:1:
/usr/include/c++/7/bits/stl_algo.h:1025:5: note: candidate: template<class _FIter, class _BinaryPredicate> _FIter std::unique(_FIter, _FIter, _BinaryPredicate)
     unique(_ForwardIterator __first, _ForwardIterator __last,
     ^~~~~~
/usr/include/c++/7/bits/stl_algo.h:1025:5: note:   template argument deduction/substitution failed:
In file included from /home/jmmacke/pisa-dev/build/CMakeFiles/CMakeTmp/src.cxx:1:0:
/home/jmmacke/pisa-dev/include/pisa/forward_index_builder.hpp:148:69: note:   deduced conflicting types for parameter ‘_FIter’ (‘pstl::execution::v1::parallel_policy’ and ‘__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > >’)
             terms.erase(std::unique(std::execution::par, first, last), last);
                                                                     ^
In file included from /home/jmmacke/pisa-dev/include/pisa/forward_index_builder.hpp:29:0,
                 from /home/jmmacke/pisa-dev/build/CMakeFiles/CMakeTmp/src.cxx:1:
/home/jmmacke/pisa-dev/include/pisa/payload_vector.hpp: In instantiation of ‘constexpr std::tuple<T ..., gsl::span<const std::byte, -1> > pisa::unpack_head(gsl::span<const std::byte>) [with T = {long unsigned int}]’:
/home/jmmacke/pisa-dev/include/pisa/payload_vector.hpp:289:36:   required from ‘static pisa::Payload_Vector<Payload_View> pisa::Payload_Vector<Payload_View>::from(gsl::span<const std::byte>) [with Payload_View = std::basic_string_view<char>; pisa::Payload_Vector<Payload_View> = pisa::Payload_Vector<>]’
/home/jmmacke/pisa-dev/include/pisa/payload_vector.hpp:281:20:   required from ‘static constexpr pisa::Payload_Vector<Payload_View> pisa::Payload_Vector<Payload_View>::from(ContiguousContainer&&) [with ContiguousContainer = pisa::MemorySource&; Payload_View = std::basic_string_view<char>; pisa::Payload_Vector<Payload_View> = pisa::Payload_Vector<>]’
/home/jmmacke/pisa-dev/include/pisa/query/term_processor.hpp:32:52:   required from here
```

**Comment by elshize** [comment]
This one is superseded by #472

**Pull request closed without merging**
