### PR TITLE
Set up WAND data for multiple scorers

### PR DESCRIPTION
**Pull request by elshize**
Investigating performance... More details to come.

### CODE REVIEW

**Comment by elshize** [comment]
@amallia @JMMackenzie I made the changes to `master` to apply changes to wand data but without adding additional scorers. But I get some pretty lame-ass results (see below). Can you guys take a look if you can find anything that might be causing it?

```
Detected performance regression!
file: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.michal-multiple-scorers.bench.ranked_or.block_simdbp.0.bench
base: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.base.bench.ranked_or.block_simdbp.0.bench
avg: 415907 --> 631658
q50: 153016 --> 219636
q90: 1244360 --> 1916000
q95: 1490780 --> 2282610

Detected performance regression!
file: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.michal-multiple-scorers.bench.ranked_and.block_simdbp.0.bench
base: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.base.bench.ranked_and.block_simdbp.0.bench
avg: 49697.9 --> 63779.1
q50: 16569 --> 19131
q90: 127130 --> 175161
q95: 195598 --> 280050

Detected performance regression!
file: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.michal-multiple-scorers.bench.wand.block_simdbp.0.bench
base: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.base.bench.wand.block_simdbp.0.bench
avg: 78768.5 --> 733211
q50: 33234 --> 249621
q90: 204016 --> 2196350
q95: 253001 --> 2625760

Detected performance regression!
file: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.michal-multiple-scorers.bench.maxscore.block_simdbp.0.bench
base: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.base.bench.maxscore.block_simdbp.0.bench
avg: 50212.3 --> 694497
q50: 29493 --> 239227
q90: 124104 --> 2061270
q95: 160989 --> 2511060

Detected performance regression!
file: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.michal-multiple-scorers.bench.block_max_wand.block_simdbp.0.bench
base: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.base.bench.block_max_wand.block_simdbp.0.bench
avg: 56752.1 --> 1082900
q50: 25786 --> 360897
q90: 128850 --> 3249220
q95: 202956 --> 3831250

Detected performance regression!
file: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.michal-multiple-scorers.bench.block_max_maxscore.block_simdbp.0.bench
base: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.base.bench.block_max_maxscore.block_simdbp.0.bench
avg: 63048.2 --> 726592
q50: 37150 --> 252801
q90: 139272 --> 2206620
q95: 195588 --> 2556970
```

**Comment by JMMackenzie** [comment]
So, our dynamic pruning algorithms seem to take as long as an exhaustive OR? Something is definitely broken with the dynamic pruning I guess. Could you do some profiling? Check how many docs are being scored, etc?

**Comment by elshize** [comment]
I have rerun the entire thing from parsing to benchmark on this branch for clueweb, and this is what I get:

```
Detected performance regression!
file: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.michal-multiple-scorers.bench.ranked_or.block_simdbp.0.bench
base: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.base.bench.ranked_or.block_simdbp.0.bench
q50: 152841 --> 156180

Detected performance regression!
file: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.michal-multiple-scorers.bench.ranked_and.block_simdbp.0.bench
base: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.base.bench.ranked_and.block_simdbp.0.bench
q90: 127081 --> 130078

Detected performance regression!
file: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.michal-multiple-scorers.bench.block_max_wand.block_simdbp.0.bench
base: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.base.bench.block_max_wand.block_simdbp.0.bench
avg: 56400.6 --> 75512.3
q50: 25824 --> 27415
q90: 128077 --> 157024
q95: 202696 --> 265292

Detected performance regression!
file: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.michal-multiple-scorers.bench.block_max_maxscore.block_simdbp.0.bench
base: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.base.bench.block_max_maxscore.block_simdbp.0.bench
q90: 139890 --> 149789
q95: 195525 --> 207308
```

The results for BMW are same as I reported before. Something in this PR slows it down. @amallia @JMMackenzie can either of you run this just to double-check? Maybe my freaking computer is broken... Anyway, if you have an idea what could cause this, let me know.

**Comment by JMMackenzie** [comment]
Thanks for following it up. It definitely seems to be a good first step as you have improved the efficiency of the other cases, but yes, perhaps there is something off with the block-max algorithms. I can take another look in the next day or two. Are we expecting this PR to have slight performance regressions, or should there be none at all?

**Comment by elshize** [comment]
I don't expect any obvious regression in this one. Thanks, I'll investigate tomorrow, and will keep you guys up to date.

**Comment by elshize** [comment]
I have actually found something interesting. Here are regressions of our **current** `master` branch vs. some earlier `master` (sadly, I don't know which commit).

```
Detected performance regression!
file: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.380246e0b5bf68aeca7e81724ee58f9a3e74d874.bench.wand.block_simdbp.0.bench
base: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.base.bench.wand.block_simdbp.0.bench
avg: 78741 --> 88525.3
q90: 204900 --> 209303
q95: 253810 --> 309281

Detected performance regression!
file: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.380246e0b5bf68aeca7e81724ee58f9a3e74d874.bench.maxscore.block_simdbp.0.bench
base: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.base.bench.maxscore.block_simdbp.0.bench
avg: 50861.3 --> 56767.9
q50: 29510 --> 31206
q90: 124016 --> 130398
q95: 160769 --> 181032

Detected performance regression!
file: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.380246e0b5bf68aeca7e81724ee58f9a3e74d874.bench.block_max_wand.block_simdbp.0.bench
base: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.base.bench.block_max_wand.block_simdbp.0.bench
q90: 128077 --> 138534
q95: 202696 --> 216707

Detected performance regression!
file: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.380246e0b5bf68aeca7e81724ee58f9a3e74d874.bench.block_max_maxscore.block_simdbp.0.bench
base: /home/michal/.jenkins/workspace/EvaluateQueries/cw09b.base.bench.block_max_maxscore.block_simdbp.0.bench
avg: 63392.5 --> 69965.1
q50: 37243 --> 40007
q90: 139890 --> 174151
q95: 195525 --> 217420
```

I'm trying to pinpoint when it started. So far tested as far back as this commit: https://github.com/pisa-engine/pisa/commit/380246e0b5bf68aeca7e81724ee58f9a3e74d874 and there results are virtually identical to those on current `master`.

**Pull request closed without merging**
