### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by elshize**
Updating documentation to reflect current `master` version.

### CODE REVIEW

**Comment by elshize** [comment]
The diagram can be found here (as it won't appear in source or on github preview): https://github.com/pisa-engine/pisa/blob/docs-update/docs/source/_static/img/pipeline.png

I'm not sure if I'm making those inter-links properly, but I think so.

**Review by JMMackenzie — APPROVED** [review]
Assuming the links work, this looks great. Nice diagram btw :-)

**Comment by elshize** [comment]
@amallia can we verify the links before merging? E.g., can I build it locally?

**Comment by amallia** [comment]
I think we shoudl rename `WAND data` in the diagram to reflect the naming we used in the OSIRRC paper (which was `Index Metadata`).

**Review by amallia — APPROVED** [review]
LGTM. just a small comment

**Comment by elshize** [comment]
I added an issue for changing the name of wand data: https://github.com/pisa-engine/pisa/issues/442 at this point let's leave it what it is in the diagram and docs, I don't want to create confusion. We should change the name everywhere at once.

**Pull request merged**
