### PR TITLE
Remove std iterator

### LINKED ISSUE #486: Replace inheritance from std::iterator
`std::iterator` was deprecated in C++17. It should be replaced by explicitly defining iterator traits. More details here: https://www.fluentcpp.com/2018/05/08/std-iterator-deprecated/https://www.fluentcpp.com/2018/05/08/std-iterator-deprecated/

I noticed it when my compiler started throwing warnings at me around the binary collection code; but there might be more instances, we should double-check.

### PR DESCRIPTION
**Pull request by elshize**
Fixes #486

### CODE REVIEW

**Review by JMMackenzie — APPROVED** [review]
Looks good, but I am now wondering what was going on with the `shards.back()` call on 281 of the test call! Just getting rid of some warning I guess?

**Comment by JMMackenzie** [comment]
Also the mac build blew up for some reason...

**Comment by elshize** [comment]
> Looks good, but I am now wondering what was going on with the shards.back() call on 281 of the test call! Just getting rid of some warning I guess?

It was just not doing anything, access to an element that's not used.

> Also the mac build blew up for some reason...

Ugh, yeah, I'll look into it when I get a chance.

**Comment by elshize** [comment]
No idea why this MacOS build fails. Doesn't seem to be related to the PR, and I have no way of investigating this. I'm going to merge it, @amallia can you give it a look and see if you can reproduce the build problems locally?

**Pull request merged**
