### PR TITLE
Binary lib

### LINKED ISSUE #305: Support Ninja builds
The `ExternalProject_Add` call for `gumbo`

https://github.com/pisa-engine/pisa/blob/master/CMakeLists.txt#L28

needs another property to support Ninja builds:

`BUILD_BYPRODUCTS ${CMAKE_BINARY_DIR}/gumbo-parser/lib/libgumbo.a`

Using it instead of `make` generator can potentially speed up compilation either now or in the future. Either way, it's an easy fix.

### PR DESCRIPTION
**Pull request by elshize**
Included in this PR: 
- Switches to a binary library as opposed to `INTERFACE` (header-only).
- Removes all algorithm includes from `queries.hpp` and moves it to a separate `algorithm.hpp` header.
- Separates implementations from `queries.hpp` to a source file `queries.cpp` included in the lib.
- Fixes some problems, mostly free functions in headers that weren't inlined now are.
- Fixes #305 by adding the required line to cmake file.

~~The reason it's `WIP` right now, is that I'm waiting for https://github.com/pisa-engine/Porter2/pull/2 to be merged and then this PR must change back to `Porter2`'s `master` branch.~~

Edit: https://github.com/pisa-engine/Porter2/pull/2 is merged now, and this PR already points to `Porter2`'s `master` branch, so this is ready for review/merge.

### CODE REVIEW

**Comment by elshize** [comment]
@amallia @JMMackenzie A review anyone?

**Review by JMMackenzie — APPROVED** [review]
Yep, looks good to me. :shipit:

**Review by JMMackenzie — CHANGES_REQUESTED** [review]
Actually, can we look at why Travis has failed first? It seems to be an issue with test cases.

**Comment by elshize** [comment]
> Actually, can we look at why Travis has failed first? It seems to be an issue with test cases.

Yeah, it failed after I merged `master`. Can't see what's up because Travis seems to be under maintenance currently. I'll look into it locally very soon.

**Comment by elshize** [comment]
@JMMackenzie Fixed, it was just a changed path problem.

**Review by JMMackenzie — APPROVED** [review]

**Review by amallia — APPROVED** [review]
LGTM. Lets fix the conflicts and merge

**Pull request merged**
