### PR TITLE
Moved to std optional

### PR DESCRIPTION
**Pull request by amallia**
Addresses https://github.com/pisa-engine/pisa/issues/47

### CODE REVIEW

**Comment by amallia** [comment]
@elshize check and merge. Just removed Boost/Optional from everywhere

**Comment by elshize** [comment]
The reason why you're now using `*optional` instead of `optional.value()` is because of apple clang thing, is that correct?

**Comment by amallia** [comment]
> The reason why you're now using *optional instead of optional.value() is because of apple clang thing, is that correct?

Yes, unless we want to drop support of early version of `AppleClang`

**Comment by elshize** [comment]
No, it's fine.

**Pull request merged**
