### PR TITLE
BMA Clean

### PR DESCRIPTION
**Pull request by JMMackenzie**
Implements #145, supersedes  #167 

This should be a part of #167 but I totally screwed up my local git repo and I thought it would be better safe than sorry.

### CODE REVIEW

**Review by amallia — APPROVED** [review]

**Comment by amallia** [comment]
Merging. Please include timings as a comment of this PR. No rush

**Comment by JMMackenzie** [comment]
Improvements for BMA with respect to Ranked AND across gov2 shown below.

```
k = 10
-------
{"type": "opt", "query": "ranked_and", "avg": 3709.64, "q50": 1454, "q90": 9611, "q95": 16093}
{"type": "opt", "query": "block_max_ranked_and", "avg": 1705.39, "q50": 967, "q90": 4989, "q95": 6829}

k = 1000
-----------
{"type": "opt", "query": "ranked_and", "avg": 3926.15, "q50": 1594, "q90": 9874, "q95": 16454}
{"type": "opt", "query": "block_max_ranked_and", "avg": 3695.37, "q50": 1931, "q90": 10906, "q95": 12607}
```

**Comment by amallia** [comment]
If you have time, could you run it using `OPTPFOR` instead of `PEF`?

**Comment by JMMackenzie** [comment]
@amallia I assume you meant `block_simdbp`? Or did you actually mean `optpfor` in this case? Below are the `block_simdbp` numbers.

```
k = 10
-------
{"type": "block_simdbp", "query": "ranked_and", "avg": 2062.18, "q50": 905, "q90": 5469, "q95": 8794}
{"type": "block_simdbp", "query": "block_max_ranked_and", "avg": 1266.92, "q50": 743, "q90": 3680, "q95": 5036}

k = 1000
--------------
{"type": "block_simdbp", "query": "ranked_and", "avg": 2258.94, "q50": 1120, "q90": 5833, "q95": 9214}
{"type": "block_simdbp", "query": "block_max_ranked_and", "avg": 2534.84, "q50": 1416, "q90": 7031, "q95": 8516}
```

**Comment by amallia** [comment]
I meant optpfor because in the original paper they used that one. Anyway any block-based one is fine.
What do you think of the results? It seems pretty good!

**Pull request merged**
